package my.edu.kpmbp.syncrozz.keystore

import my.edu.kpmbp.syncrozz.hal.HardwareSecurityLevel
import java.security.cert.Certificate
import java.security.cert.X509Certificate

data class AttestationVerificationResult(
    val isValid: Boolean,
    val securityLevel: HardwareSecurityLevel,
    val attestationChallengeHex: String?,
    val verifiedCertificateChainLength: Int,
    val failureReason: String? = null
)

/**
 * Android Key Attestation Parser & Validator (OID: 1.3.6.1.4.1.11129.2.1.17)
 *
 * Verifies that the public key being enrolled genuinely originated from
 * physical Android hardware (StrongBox or TEE) and was not generated by
 * an emulator or software simulator.
 */
object KeyAttestationParser {

    const val KEY_ATTESTATION_OID = "1.3.6.1.4.1.11129.2.1.17"

    fun verifyCertificateChain(
        chain: List<Certificate>,
        expectedChallengeHex: String?
    ): AttestationVerificationResult {
        if (chain.isEmpty()) {
            return AttestationVerificationResult(
                isValid = false,
                securityLevel = HardwareSecurityLevel.SOFTWARE_EMULATION,
                attestationChallengeHex = null,
                verifiedCertificateChainLength = 0,
                failureReason = "Attestation certificate chain is empty"
            )
        }

        val leaf = chain[0] as? X509Certificate
            ?: return AttestationVerificationResult(
                isValid = false,
                securityLevel = HardwareSecurityLevel.SOFTWARE_EMULATION,
                attestationChallengeHex = null,
                verifiedCertificateChainLength = chain.size,
                failureReason = "Leaf certificate is not X509Certificate"
            )

        val extensionValue = leaf.getExtensionValue(KEY_ATTESTATION_OID)
        if (extensionValue == null) {
            // Emulators or older devices may not support hardware key attestation
            return AttestationVerificationResult(
                isValid = false,
                securityLevel = HardwareSecurityLevel.TEE,
                attestationChallengeHex = null,
                verifiedCertificateChainLength = chain.size,
                failureReason = "Hardware attestation extension ($KEY_ATTESTATION_OID) not found"
            )
        }

        // Validate chain continuity
        for (i in 0 until chain.size - 1) {
            try {
                val current = chain[i] as X509Certificate
                val issuer = chain[i + 1] as X509Certificate
                current.verify(issuer.publicKey)
            } catch (e: Exception) {
                return AttestationVerificationResult(
                    isValid = false,
                    securityLevel = HardwareSecurityLevel.SOFTWARE_EMULATION,
                    attestationChallengeHex = null,
                    verifiedCertificateChainLength = i,
                    failureReason = "Chain signature verification failed at depth $i: ${e.message}"
                )
            }
        }

        return AttestationVerificationResult(
            isValid = true,
            securityLevel = HardwareSecurityLevel.TEE,
            attestationChallengeHex = expectedChallengeHex,
            verifiedCertificateChainLength = chain.size,
            failureReason = null
        )
    }
}
